### ISSUE TITLE
KeyError: 'generate_furigana_no_kanji' in Anki 2.1.54

### ISSUE THREAD

**Issue by homocomputeris** [Ajatt-Tools/Furigana#3]
I'm using the `master` build of Anki. AJT furigana seems to crash in that version, and probably it will affect future releases.

To reproduce:
1. Open browser
2. Right-click on any field in the browser's editor

Anki 2.1.54 (e6f158e4) Python 3.10.5 Qt 5.15.4 PyQt 5.15.7
Platform: Linux
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2022-06-28 00:11:24
Possible reason: ⁨AJT Furigana⁩
```
Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/editor.py", line 1359, in contextMenuEvent
    gui_hooks.editor_will_show_context_menu(self, m)
  File "/usr/lib/python3.10/site-packages/aqt/hooks_gen.py", line 2372, in __call__
    hook(editor_webview, menu)
  File "/home/user/.local/share/Anki2/addons21/1344485230/context_menu.py", line 76, in add_context_menu_items
    if Action.enabled():
  File "/home/user/.local/share/Anki2/addons21/1344485230/context_menu.py", line 29, in enabled
    return config['context_menu'][cls.key]
KeyError: 'generate_furigana_no_kanji'
```

**Comment by tatsumoto-ren** [comment]
See [issue.md](https://github.com/Ajatt-Tools/Furigana/blob/main/.github/ISSUE_TEMPLATE/issue.md)
